# This file adapted from github.com/antespi/docker-imap-devel
version: "3"

services:
  imap:
    image: antespi/docker-imap-devel:latest
    container_name: imap
    ports:
    - "8993:993"
    environment:
    - MAILNAME=example.com
    - MAIL_ADDRESS=address@example.com
    - MAIL_PASS=pass
  other-imap:
    image: antespi/docker-imap-devel:latest
    container_name: other-imap
    ports:
    - "9993:993"
    environment:
    - MAILNAME=other.org
    - MAIL_ADDRESS=email@other.org
    - MAIL_PASS=pass
