# This file adapted from github.com/antespi/docker-imap-devel
version: "3"

services:
  imap:
    image: ghcr.io/joeyates/docker-imap-devel@sha256:6d6a64c32e2c583222d75286aa46a04ada5aea76efa36117815bf0e19d5063b6
    container_name: imap
    environment:
    - MAILNAME=example.com
    - MAIL_ADDRESS=address@example.com
    - MAIL_PASS=pass
  other-imap:
    image: ghcr.io/joeyates/docker-imap-devel@sha256:6d6a64c32e2c583222d75286aa46a04ada5aea76efa36117815bf0e19d5063b6
    container_name: other-imap
    environment:
    - MAILNAME=other.org
    - MAIL_ADDRESS=email@other.org
    - MAIL_PASS=pass
    - DOVECOT_PUBLIC_NAMESPACE_PREFIX=other_public
  imap-backup:
    build:
      context: .
      args:
      - BUNDLER_VERSION
      - RUBY_VERSION
    image: imap-backup:${RUBY_VERSION}
    container_name: imap-backup
    tty: true
    stdin_open: true
    environment:
    - RUBY_VERSION=$RUBY_VERSION
    - BUNDLE_PATH=/app/vendor
    - BUNDLE_BINSTUBS=/app/bin/stubs
    - DOCKER_HOST_IMAP=imap
    - DOCKER_PORT_IMAP=993
    - DOCKER_HOST_OTHER_IMAP=other-imap
    - DOCKER_PORT_OTHER_IMAP=993
    - HOME=/app
    volumes:
    - ..:/app
