# This file adapted from github.com/antespi/docker-imap-devel
version: "3"

services:
  imap:
    image: antespi/docker-imap-devel:latest
    container_name: imap
    environment:
    - MAILNAME=example.com
    - MAIL_ADDRESS=address@example.com
    - MAIL_PASS=pass
  other-imap:
    image: antespi/docker-imap-devel:latest
    container_name: other-imap
    environment:
    - MAILNAME=other.org
    - MAIL_ADDRESS=email@other.org
    - MAIL_PASS=pass
  imap-backup:
    build:
      context: .
      args:
      - RUBY_VERSION
    image: imap-backup:${RUBY_VERSION}
    container_name: imap-backup
    tty: true
    stdin_open: true
    user: $ID
    environment:
    - RUBY_VERSION=$RUBY_VERSION
    - BUNDLE_PATH=/app/vendor
    - BUNDLE_BINSTUBS=./bin/stubs
    - DOCKER_HOST_IMAP=imap
    - DOCKER_PORT_IMAP=993
    - DOCKER_HOST_OTHER_IMAP=other-imap
    - DOCKER_PORT_OTHER_IMAP=993
    - HOME=/app
    volumes:
      - ../..:/app
